sonar.projectKey=Axyra---Sistema-de-nomina
sonar.projectName=Axyra - Sistema de nomina
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**,**/.github/**,**/*.log
sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=4096
sonar.typescript.node.maxspace=4096
