-- Crear tabla para almacenar tokens de Google Drive
CREATE TABLE IF NOT EXISTS user_google_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  access_token TEXT NOT NULL,
  refresh_token TEXT,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  token_type TEXT NOT NULL DEFAULT 'Bearer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  CONSTRAINT user_google_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- Crear índice para búsquedas rápidas
CREATE INDEX IF NOT EXISTS user_google_tokens_user_id_idx ON user_google_tokens(user_id);

-- Habilitar RLS
ALTER TABLE user_google_tokens ENABLE ROW LEVEL SECURITY;

-- Política: Los usuarios solo pueden ver sus propios tokens
CREATE POLICY "Users can view own tokens"
  ON user_google_tokens
  FOR SELECT
  USING (auth.uid() = user_id);

-- Política: Los usuarios solo pueden insertar sus propios tokens
CREATE POLICY "Users can insert own tokens"
  ON user_google_tokens
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Política: Los usuarios solo pueden actualizar sus propios tokens
CREATE POLICY "Users can update own tokens"
  ON user_google_tokens
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Política: Los usuarios solo pueden eliminar sus propios tokens
CREATE POLICY "Users can delete own tokens"
  ON user_google_tokens
  FOR DELETE
  USING (auth.uid() = user_id);
